#ifndef dbg_servoctrl_h
#define dbg_servoctrl_h
#define SIMAVR
#include "dbg_simavr.h"

// simulator debugging for servoctrl.h
AVR_MCU_VCD_REGISTER(DDRB);
AVR_MCU_VCD_REGISTER(ICR1H);
AVR_MCU_VCD_REGISTER(ICR1L);
AVR_MCU_VCD_ALL_IRQ();
AVR_MCU_VCD_REGISTER(OCR1AH);
AVR_MCU_VCD_REGISTER(OCR1AL);
AVR_MCU_VCD_PORT_PIN('B', 1, "PB1");
AVR_MCU_VCD_REGISTER(SREG);
AVR_MCU_VCD_REGISTER(TCCR1A);
AVR_MCU_VCD_REGISTER(TCCR1B);
AVR_MCU_VCD_REGISTER(TIFR1);
AVR_MCU_VCD_REGISTER(TIMSK1);
AVR_MCU_VCD_REGISTER(TCNT1H);
AVR_MCU_VCD_REGISTER(TCNT1L);

#endif
